### ISSUE TITLE
Mass Downloader

### ISSUE THREAD

**Issue by manalshaikh** [SomilGumber/wpextractor#4]
Mass-downloader will be an arg based downloader where the user will provide the text file in the following format : 
https://abcd1.com
https://xyza.com

and etc.. 
The script should run like this.

For direct and single URL extraction, use `python extract.py -u http://abcd.com` and for multiple URL, supply outside text file with command example be `python extract.py -l urllist.txt` where "l"(L) stands for the list of the URL and urllist.txt explains the URL.

**Comment by SomilGumber** [comment]
da39ad85709c872a2e6488597df6b2fed028f99e
